const phrases = [
	"Stop being a lazy excuse for a human being. You’re better than this... but barely 💀.",
	"Get off your ass. The world’s not going to wait for you to stop whining 😂.",
	"If you’re not willing to work for it, don’t bother pretending you want it 🚮.",
	"Quit being a joke. The only thing you’re wasting is potential 🐌.",
	"You can do it, but don’t expect a medal for the bare minimum 🤡.",
	"You're not tired, you're just lazy. Get back to work 🤢.",
	"The only thing holding you back is your pathetic excuses 🤮.",
	"The world doesn’t care about your feelings. Get to work 😖.",
	"You don't need motivation, you need discipline. Stop being soft 💩.",
	"Stop hoping for a miracle; miracles don’t happen for people who refuse to try 🤬.",
	"Your 'hard work' is laughable. Try again with a little effort next time 💀.",
	"If you can’t handle a little grind, then what makes you think you’ll ever get anywhere? 😂",
	"Procrastination isn’t a personality trait, it’s a lack of willpower 🤡.",
	"Stop whining and start doing. Nobody owes you success 🚮.",
	"You’re not a victim, you’re just lazy. Get up and do something 🐌.",
	"Success isn’t handed to you. It’s earned. Something you clearly haven’t figured out yet 🤢.",
	"Excuses are for the weak. You're stronger than that. So prove it 💩.",
	"Being busy isn’t the same as being productive. You know that, right 🤬?",
	"If you keep making excuses, you’re never going to get anywhere 🤮.",
	"Failure isn’t your enemy; laziness is 🤡.",
	"You can either make progress or stay pathetic. Your choice 💀.",
	"You have all the excuses in the world, but none of them matter if you don’t work 🚮.",
	"No one cares about your sob story. Get off your ass and hustle 🐌.",
	"If you want results, you have to stop making excuses and start making sacrifices 🤡.",
	"Stop lying to yourself. You're not tired, you're just lazy 💩.",
	"You’re capable of more than this pathetic display. Start acting like it 🤬.",
	"Stop scrolling through your phone like your life depends on it. It doesn't 😂.",
	"Your phone isn’t your life. Put it down and actually live 💀.",
	"You can't change the world if you're too busy doomscrolling on your phone 🤡.",
	"The more you check your phone, the further away you get from your goals 🚮.",
	"Put your phone down. It's not a productivity tool, it's a time thief 🐌.",
	"How about using that phone for something other than wasting time 🤬?",
	"Every minute you spend scrolling is a minute you’ll never get back 💩.",
	"Your phone is stealing your life. Cut the addiction, get back to work 🤢.",
	"That phone is a prison, and you’re locked up 🤮. Break free.",
	"Stop mindlessly checking your phone like a zombie. It’s pathetic 💀.",
	"You’re not productive; you’re just scrolling aimlessly like a robot 🤡.",
	"That phone in your hand is keeping you from success. Drop it 🐌.",
	"The more time you waste on your phone, the further you are from your dreams 🤬.",
	"That screen isn’t going to make you successful. Put it away and get to work 🚮.",
	"You’re wasting your life, one scroll at a time 💩.",
	"That phone addiction is going to ruin you if you don’t put it down 🤡.",
	"Instead of scrolling for hours, try actually doing something that matters 💀.",
	"Your phone isn’t a tool for progress, it’s a distraction. Stop feeding the addiction 🐌.",
	"Get off your phone and stop wasting precious time. You’ll never get it back 🤮.",
	"If your phone is your biggest distraction, you’re never going to make it 💩.",
	"Stop using your phone as a way to avoid the real world 🚮.",
	"Every second on your phone is a second you're not working towards your goals 🐌.",
	"That phone isn’t giving you happiness; it’s giving you anxiety and wasted time 🤬.",
	"You can’t build a future if you’re glued to your phone screen 💀.",
	"Your addiction to your phone is what’s holding you back from greatness 🤢.",
];

const randomPhrase = function () {
	return phrases[Math.floor(Math.random() * phrases.length)];
};

export default randomPhrase;
